### ISSUE TITLE
오타 관련 제보 드려요

### ISSUE THREAD

**Issue by soomtong** [lezhin/apply#4]
README 에만 있는 줄 알고 한 파일 즉시 PR 드렸는데 (사실 이것도 좀 무례했습니다.)
여러 곳에 '생일날' 이라고 사용이 되었네요.

이미 아시겠지만 역전 앞 같은 표현이니 고쳐주시면 더 좋을 것 같아요.

감사합니다.

**Comment by xguru** [comment]
수정되었습니다. 고맙습니다!
