### ISSUE TITLE
https://tech.lezhin.com/ RSS 확인 부탁드립니다

### ISSUE THREAD

**Issue by ChangJoo-Park** [lezhin/apply#7]
안녕하세요 

[스타트업 기술 블로그 모음](https://metapost.dev/) 을 운영하고 있는 박창주 입니다.

기술 블로그를 보다가 [RSS](https://tech.lezhin.com/rss/) 가 작동하지 않는 것을 발견하고 고쳐주실 수 있을까 싶어 문의 드립니다

꼭 스타트업 기술 블로그 모음 때문이 아니더라도 회사의 블로그를 RSS로 구독하고 싶어하는 분들이 계실 것 같습니다.
시간이 되실 때 한번 확인해주실 수 있을까요?

좋은 글을 많이 올려주셔서 감사합니다.
이 저장소에 이슈로 올려서 죄송합니다 이해 부탁드려요

---

아래 링크는 스타트업 기술 블로그 모음 소개 입니다
https://medium.com/@changjoopark/%EC%8A%A4%ED%83%80%ED%8A%B8%EC%97%85-%EA%B8%B0%EC%88%A0-%EB%B8%94%EB%A1%9C%EA%B7%B8-%EB%AA%A8%EC%9D%8C%EC%9D%84-%EB%A7%8C%EB%93%A4%EB%A9%B0-da1ba22627f1

**Comment by ghost** [comment]
잘못 보내셨어요
​
-----Original Message-----

**Comment by euanjeon** [comment]
잘못보내셨어요

2020년 6월 24일 (수) 오후 12:24, ChangJoo Park(박창주) <notifications@github.com>님이
작성:
